### ISSUE TITLE
Automatically pull the image if it's missing

### ISSUE THREAD

**Issue by smashwilson** [cloudpipe/cloudpipe#31]
This would save us a setup step that I always forget to do. Otherwise, you see this:

```
cloudpipe_1 | time="2014-12-31T17:11:02Z" level="info" msg="Launching a job." account="admin" jid=2 
cloudpipe_1 | time="2014-12-31T17:11:02Z" level="error" msg="Created the job's container: ERROR" account="admin" err="no such image" jid=2 
```

**Comment by rgbkrk** [comment]
Oh whoops. I duped this in #37.

In the same vein as we did with tmpnb, we don't have the service pull new images here. Seemed like a good decision, but we could do it as part of cloudpipe itself. Check out #38 to see what I ended up doing.
