### ISSUE TITLE
Change _id with insert op, not update

### ISSUE THREAD

**Issue by jrperritt** [cloudpipe/cloudpipe#65]
Similar to #63, this Update function will likely need to be changed:
https://github.com/cloudpipe/cloudpipe/blob/f87bc835490e18914b8dc996a38941615b8a56c5/storage.go#L208

**Comment by rgbkrk** [comment]
Yup, after #63 is fixed this is the next one on the chopping block.

```
INFO[7179] Launching a job.                              account=cloudpi jid=2
DEBU[7179] Created the job's container: ok               account=cloudpi jid=2
ERRO[7179] Unable to update the job's start timestamp and container id.  account=cloudpi err=exception: Mod on _id not allowed jid=2
```

**Comment by jrperritt** [comment]
Closing. Upgrading to MongoDB >= 2.6 fixed this.
