### ISSUE TITLE
Possibly Incompatible with Mongo over SSL

### ISSUE THREAD

**Issue by rgbkrk** [cloudpipe/cloudpipe#66]
ObjectRocket has both a plaintext and an SSL endpoint for Mongo instances. Thus far, we've only been able to get it to connect over the plaintext connection (thanks for troubleshooting that @jrperritt!)

Perhaps options need to be passed to mgo? I'm not seeing anything good in [DialInfo](http://godoc.org/labix.org/v2/mgo#DialInfo), so it may be something that needs to be added to that driver. ObjectRocket's docs also recommend using stunnel.

**Comment by rgbkrk** [comment]
Ah, it might be `Mechanism` with `MONGODB-X509`!

**Comment by rgbkrk** [comment]
Looks like I'll need to make a PR with some extra options handling.

**Comment by rgbkrk** [comment]
Oooh, even better. It can be tacked on to the mongodb URL. That requires no code changes, just configuration.

**Comment by rgbkrk** [comment]
`mgo` doesn't currently support ssl. Upstream issue here: https://github.com/go-mgo/mgo/issues/84

**Comment by jrperritt** [comment]
@rgbkrk You might want to have a go at specifying the `DialServer` function in the `DialInfo` object and within `DialServer` calling the `Dial` function from the `tls` package.
Reference: http://golang.org/pkg/crypto/tls/#Dial
That's what I was going to try tomorrow.

**Comment by rgbkrk** [comment]
Neat, if that works out it would be a good submission to mgo.

ObjectRocket support also mentioned that we can connect over service net (which we should do anyway) and use stunnel, using URLs like:

```
iad-sn-mongos2.objectrocket.com
```

**Comment by rgbkrk** [comment]
Hmmm, looks like mgo's `Dial` field in `DialInfo` is obsolete. I'm not sure how well these line up with golang stdlib's `Dial` and `DialServer` (again, I'm new here).

https://github.com/go-mgo/mgo/blob/7a4943433e00707e38099a2b2e904d96681d14bc/session.go#L337-L342

**Comment by rgbkrk** [comment]
[SSL support in mgo, topic on the mailing list](https://groups.google.com/forum/#!topic/mgo-users/44Uy4dc6o00)

**Comment by smashwilson** [comment]
Well that's dandy. Yeah, this'll probably take a PR to mgo to fix.

**Comment by rgbkrk** [comment]
The way I read that thread is that they don't want to put generic support in (since TLS requires a config).

**Comment by jrperritt** [comment]
SSL is supported via `mgo.DialInfo` by specifying the `DialServer` function with.

**Comment by rgbkrk** [comment]
Welp, now ParseURL is public. https://github.com/go-mgo/mgo/pull/85
